# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RobotUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 656)
        Dialog.setMinimumSize(QtCore.QSize(470, 320))
        Dialog.setMaximumSize(QtCore.QSize(1200, 1000))
        Dialog.setSizeIncrement(QtCore.QSize(470, 320))
        Dialog.setBaseSize(QtCore.QSize(470, 320))
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setStyleSheet("")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(5, 0, 1191, 606))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.tabWidget.setMaximumSize(QtCore.QSize(1200, 1000))
        self.tabWidget.setBaseSize(QtCore.QSize(450, 300))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 500, 566))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.doubleSpinBox_rotation = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_rotation.setEnabled(False)
        self.doubleSpinBox_rotation.setGeometry(QtCore.QRect(125, 290, 62, 22))
        self.doubleSpinBox_rotation.setDecimals(1)
        self.doubleSpinBox_rotation.setMinimum(1.0)
        self.doubleSpinBox_rotation.setMaximum(1000.0)
        self.doubleSpinBox_rotation.setSingleStep(0.1)
        self.doubleSpinBox_rotation.setObjectName("doubleSpinBox_rotation")
        self.doubleSpinBox_step = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_step.setEnabled(False)
        self.doubleSpinBox_step.setGeometry(QtCore.QRect(125, 255, 62, 22))
        self.doubleSpinBox_step.setDecimals(1)
        self.doubleSpinBox_step.setMinimum(1.0)
        self.doubleSpinBox_step.setMaximum(1000.0)
        self.doubleSpinBox_step.setSingleStep(0.1)
        self.doubleSpinBox_step.setObjectName("doubleSpinBox_step")
        self.label_move_step = QtWidgets.QLabel(self.groupBox)
        self.label_move_step.setGeometry(QtCore.QRect(15, 255, 86, 21))
        self.label_move_step.setObjectName("label_move_step")
        self.label_move_step_2 = QtWidgets.QLabel(self.groupBox)
        self.label_move_step_2.setGeometry(QtCore.QRect(15, 290, 96, 21))
        self.label_move_step_2.setObjectName("label_move_step_2")
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setGeometry(QtCore.QRect(205, 255, 31, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        self.label_44.setGeometry(QtCore.QRect(205, 290, 47, 21))
        self.label_44.setObjectName("label_44")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 35, 196, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_Step = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_Step.setFont(font)
        self.radioButton_Step.setObjectName("radioButton_Step")
        self.horizontalLayout.addWidget(self.radioButton_Step)
        self.radioButton_Jogging = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Jogging.setFont(font)
        self.radioButton_Jogging.setChecked(True)
        self.radioButton_Jogging.setObjectName("radioButton_Jogging")
        self.horizontalLayout.addWidget(self.radioButton_Jogging)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(405, 520, 86, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(215, 520, 86, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 520, 86, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 125, 482, 99))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_xUp = QtWidgets.QPushButton(self.layoutWidget)
        self.button_xUp.setObjectName("button_xUp")
        self.gridLayout.addWidget(self.button_xUp, 0, 0, 1, 1)
        self.button_yUp = QtWidgets.QPushButton(self.layoutWidget)
        self.button_yUp.setObjectName("button_yUp")
        self.gridLayout.addWidget(self.button_yUp, 0, 1, 1, 1)
        self.button_zUp = QtWidgets.QPushButton(self.layoutWidget)
        self.button_zUp.setObjectName("button_zUp")
        self.gridLayout.addWidget(self.button_zUp, 0, 2, 1, 1)
        self.button_rollUp = QtWidgets.QPushButton(self.layoutWidget)
        self.button_rollUp.setObjectName("button_rollUp")
        self.gridLayout.addWidget(self.button_rollUp, 0, 3, 1, 1)
        self.button_pitchUp = QtWidgets.QPushButton(self.layoutWidget)
        self.button_pitchUp.setObjectName("button_pitchUp")
        self.gridLayout.addWidget(self.button_pitchUp, 0, 4, 1, 1)
        self.button_yawUp = QtWidgets.QPushButton(self.layoutWidget)
        self.button_yawUp.setObjectName("button_yawUp")
        self.gridLayout.addWidget(self.button_yawUp, 0, 5, 1, 1)
        self.lineEdit_x = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.gridLayout.addWidget(self.lineEdit_x, 1, 0, 1, 1)
        self.lineEdit_y = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.gridLayout.addWidget(self.lineEdit_y, 1, 1, 1, 1)
        self.lineEdit_z = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_z.setObjectName("lineEdit_z")
        self.gridLayout.addWidget(self.lineEdit_z, 1, 2, 1, 1)
        self.lineEdit_roll = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.gridLayout.addWidget(self.lineEdit_roll, 1, 3, 1, 1)
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.gridLayout.addWidget(self.lineEdit_pitch, 1, 4, 1, 1)
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.gridLayout.addWidget(self.lineEdit_yaw, 1, 5, 1, 1)
        self.button_xDown = QtWidgets.QPushButton(self.layoutWidget)
        self.button_xDown.setObjectName("button_xDown")
        self.gridLayout.addWidget(self.button_xDown, 2, 0, 1, 1)
        self.button_yDown = QtWidgets.QPushButton(self.layoutWidget)
        self.button_yDown.setObjectName("button_yDown")
        self.gridLayout.addWidget(self.button_yDown, 2, 1, 1, 1)
        self.button_zDown = QtWidgets.QPushButton(self.layoutWidget)
        self.button_zDown.setObjectName("button_zDown")
        self.gridLayout.addWidget(self.button_zDown, 2, 2, 1, 1)
        self.button_rollDown = QtWidgets.QPushButton(self.layoutWidget)
        self.button_rollDown.setObjectName("button_rollDown")
        self.gridLayout.addWidget(self.button_rollDown, 2, 3, 1, 1)
        self.button_pitchDown = QtWidgets.QPushButton(self.layoutWidget)
        self.button_pitchDown.setObjectName("button_pitchDown")
        self.gridLayout.addWidget(self.button_pitchDown, 2, 4, 1, 1)
        self.button_yawDown = QtWidgets.QPushButton(self.layoutWidget)
        self.button_yawDown.setObjectName("button_yawDown")
        self.gridLayout.addWidget(self.button_yawDown, 2, 5, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setEnabled(False)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 355, 482, 99))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_JUp_1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JUp_1.setEnabled(False)
        self.button_JUp_1.setObjectName("button_JUp_1")
        self.gridLayout_2.addWidget(self.button_JUp_1, 0, 0, 1, 1)
        self.button_JUp_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JUp_2.setEnabled(False)
        self.button_JUp_2.setObjectName("button_JUp_2")
        self.gridLayout_2.addWidget(self.button_JUp_2, 0, 1, 1, 1)
        self.button_JUp_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JUp_3.setEnabled(False)
        self.button_JUp_3.setObjectName("button_JUp_3")
        self.gridLayout_2.addWidget(self.button_JUp_3, 0, 2, 1, 1)
        self.button_JUp_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JUp_4.setEnabled(False)
        self.button_JUp_4.setObjectName("button_JUp_4")
        self.gridLayout_2.addWidget(self.button_JUp_4, 0, 3, 1, 1)
        self.button_JUp_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JUp_5.setEnabled(False)
        self.button_JUp_5.setObjectName("button_JUp_5")
        self.gridLayout_2.addWidget(self.button_JUp_5, 0, 4, 1, 1)
        self.button_JUp_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JUp_6.setEnabled(False)
        self.button_JUp_6.setObjectName("button_JUp_6")
        self.gridLayout_2.addWidget(self.button_JUp_6, 0, 5, 1, 1)
        self.lineEdit_J_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_J_1.setEnabled(False)
        self.lineEdit_J_1.setObjectName("lineEdit_J_1")
        self.gridLayout_2.addWidget(self.lineEdit_J_1, 1, 0, 1, 1)
        self.lineEdit_J_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_J_2.setEnabled(False)
        self.lineEdit_J_2.setObjectName("lineEdit_J_2")
        self.gridLayout_2.addWidget(self.lineEdit_J_2, 1, 1, 1, 1)
        self.lineEdit_J_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_J_3.setEnabled(False)
        self.lineEdit_J_3.setObjectName("lineEdit_J_3")
        self.gridLayout_2.addWidget(self.lineEdit_J_3, 1, 2, 1, 1)
        self.lineEdit_J_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_J_4.setEnabled(False)
        self.lineEdit_J_4.setObjectName("lineEdit_J_4")
        self.gridLayout_2.addWidget(self.lineEdit_J_4, 1, 3, 1, 1)
        self.lineEdit_J_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_J_5.setEnabled(False)
        self.lineEdit_J_5.setObjectName("lineEdit_J_5")
        self.gridLayout_2.addWidget(self.lineEdit_J_5, 1, 4, 1, 1)
        self.lineEdit_J_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_J_6.setEnabled(False)
        self.lineEdit_J_6.setObjectName("lineEdit_J_6")
        self.gridLayout_2.addWidget(self.lineEdit_J_6, 1, 5, 1, 1)
        self.button_JDown_1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JDown_1.setEnabled(False)
        self.button_JDown_1.setObjectName("button_JDown_1")
        self.gridLayout_2.addWidget(self.button_JDown_1, 2, 0, 1, 1)
        self.button_JDown_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JDown_2.setEnabled(False)
        self.button_JDown_2.setObjectName("button_JDown_2")
        self.gridLayout_2.addWidget(self.button_JDown_2, 2, 1, 1, 1)
        self.button_JDown_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JDown_3.setEnabled(False)
        self.button_JDown_3.setObjectName("button_JDown_3")
        self.gridLayout_2.addWidget(self.button_JDown_3, 2, 2, 1, 1)
        self.button_JDown_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JDown_4.setEnabled(False)
        self.button_JDown_4.setObjectName("button_JDown_4")
        self.gridLayout_2.addWidget(self.button_JDown_4, 2, 3, 1, 1)
        self.button_JDown_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JDown_5.setEnabled(False)
        self.button_JDown_5.setObjectName("button_JDown_5")
        self.gridLayout_2.addWidget(self.button_JDown_5, 2, 4, 1, 1)
        self.button_JDown_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_JDown_6.setEnabled(False)
        self.button_JDown_6.setObjectName("button_JDown_6")
        self.gridLayout_2.addWidget(self.button_JDown_6, 2, 5, 1, 1)
        self.label_rotation_step = QtWidgets.QLabel(self.widget)
        self.label_rotation_step.setGeometry(QtCore.QRect(230, 700, 91, 16))
        self.label_rotation_step.setObjectName("label_rotation_step")
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget_4.setGeometry(QtCore.QRect(510, 5, 666, 571))
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_7)
        self.groupBox_9.setGeometry(QtCore.QRect(5, 0, 661, 566))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.groupBox_9)
        self.treeWidget_2.setGeometry(QtCore.QRect(10, 25, 311, 531))
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.stackedWidget_4.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_4.addWidget(self.page_8)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget.setGeometry(QtCore.QRect(5, 10, 170, 560))
        self.treeWidget.setStyleSheet("")
        self.treeWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.treeWidget.setDragEnabled(False)
        self.treeWidget.setDragDropOverwriteMode(False)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setWordWrap(False)
        self.treeWidget.setExpandsOnDoubleClick(True)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(0, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 0, 996, 576))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 390, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_tollX = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_tollX.setGeometry(QtCore.QRect(50, 65, 91, 20))
        self.lineEdit_tollX.setMaxLength(10)
        self.lineEdit_tollX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tollX.setObjectName("lineEdit_tollX")
        self.lineEdit_tool_Y = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_tool_Y.setGeometry(QtCore.QRect(50, 95, 91, 20))
        self.lineEdit_tool_Y.setMaxLength(10)
        self.lineEdit_tool_Y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tool_Y.setObjectName("lineEdit_tool_Y")
        self.lineEdit_tool_Z = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_tool_Z.setGeometry(QtCore.QRect(50, 125, 91, 20))
        self.lineEdit_tool_Z.setMaxLength(10)
        self.lineEdit_tool_Z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tool_Z.setObjectName("lineEdit_tool_Z")
        self.lineEdit_tool_RX = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_tool_RX.setGeometry(QtCore.QRect(50, 200, 91, 20))
        self.lineEdit_tool_RX.setMaxLength(10)
        self.lineEdit_tool_RX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tool_RX.setObjectName("lineEdit_tool_RX")
        self.lineEdit_tool_RY = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_tool_RY.setGeometry(QtCore.QRect(50, 230, 91, 20))
        self.lineEdit_tool_RY.setMaxLength(10)
        self.lineEdit_tool_RY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tool_RY.setObjectName("lineEdit_tool_RY")
        self.lineEdit_tool_RZ = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_tool_RZ.setGeometry(QtCore.QRect(50, 260, 91, 20))
        self.lineEdit_tool_RZ.setMaxLength(10)
        self.lineEdit_tool_RZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tool_RZ.setObjectName("lineEdit_tool_RZ")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 65, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 95, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 125, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(150, 65, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(150, 95, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(150, 125, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 200, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(150, 200, 21, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(150, 230, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(150, 260, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 35, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 170, 81, 16))
        self.label_14.setObjectName("label_14")
        self.resetToll_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.resetToll_Button.setGeometry(QtCore.QRect(300, 260, 76, 23))
        self.resetToll_Button.setObjectName("resetToll_Button")
        self.setPoints_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.setPoints_Button.setGeometry(QtCore.QRect(215, 260, 75, 23))
        self.setPoints_Button.setObjectName("setPoints_Button")
        self.setTool_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.setTool_Button.setEnabled(True)
        self.setTool_Button.setGeometry(QtCore.QRect(300, 100, 76, 26))
        self.setTool_Button.setObjectName("setTool_Button")
        self.tollsComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.tollsComboBox.setGeometry(QtCore.QRect(260, 30, 114, 26))
        self.tollsComboBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tollsComboBox.setMaxVisibleItems(10)
        self.tollsComboBox.setMaxCount(14)
        self.tollsComboBox.setObjectName("tollsComboBox")
        self.tollsComboBox.addItem("")
        self.addToolButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addToolButton.setGeometry(QtCore.QRect(215, 30, 31, 26))
        self.addToolButton.setObjectName("addToolButton")
        self.removeToolButton = QtWidgets.QPushButton(self.groupBox_2)
        self.removeToolButton.setGeometry(QtCore.QRect(215, 65, 31, 26))
        self.removeToolButton.setObjectName("removeToolButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 65, 116, 26))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(260, 30, 115, 26))
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setMaxLength(15)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page)
        self.stackedWidget_2.setEnabled(True)
        self.stackedWidget_2.setGeometry(QtCore.QRect(410, 0, 591, 571))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QtCore.QRect(5, 0, 581, 571))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(85, 25, 201, 531))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/PulseAddones/RobotMovingPanel/images/211402.png"))
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setGeometry(QtCore.QRect(330, 35, 180, 516))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/PulseAddones/RobotMovingPanel/images/211833.png"))
        self.label_19.setObjectName("label_19")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 0, 580, 570))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.setToolPoint_1_Button = QtWidgets.QPushButton(self.groupBox_3)
        self.setToolPoint_1_Button.setGeometry(QtCore.QRect(140, 130, 171, 41))
        self.setToolPoint_1_Button.setObjectName("setToolPoint_1_Button")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.setToolPoint_1_Button)
        self.setToolPoint_2_Button = QtWidgets.QPushButton(self.groupBox_3)
        self.setToolPoint_2_Button.setEnabled(True)
        self.setToolPoint_2_Button.setGeometry(QtCore.QRect(140, 180, 171, 41))
        self.setToolPoint_2_Button.setObjectName("setToolPoint_2_Button")
        self.buttonGroup.addButton(self.setToolPoint_2_Button)
        self.setToolPoint_3_Button = QtWidgets.QPushButton(self.groupBox_3)
        self.setToolPoint_3_Button.setEnabled(True)
        self.setToolPoint_3_Button.setGeometry(QtCore.QRect(140, 230, 171, 41))
        self.setToolPoint_3_Button.setObjectName("setToolPoint_3_Button")
        self.buttonGroup.addButton(self.setToolPoint_3_Button)
        self.setToolPoint_4_Button = QtWidgets.QPushButton(self.groupBox_3)
        self.setToolPoint_4_Button.setEnabled(True)
        self.setToolPoint_4_Button.setGeometry(QtCore.QRect(140, 280, 171, 41))
        self.setToolPoint_4_Button.setObjectName("setToolPoint_4_Button")
        self.buttonGroup.addButton(self.setToolPoint_4_Button)
        self.SetToolPointsButton = QtWidgets.QPushButton(self.groupBox_3)
        self.SetToolPointsButton.setEnabled(False)
        self.SetToolPointsButton.setGeometry(QtCore.QRect(140, 360, 171, 31))
        self.SetToolPointsButton.setObjectName("SetToolPointsButton")
        self.cancelSetToolPointsButton = QtWidgets.QPushButton(self.groupBox_3)
        self.cancelSetToolPointsButton.setGeometry(QtCore.QRect(320, 360, 111, 31))
        self.cancelSetToolPointsButton.setObjectName("cancelSetToolPointsButton")
        self.Discription = QtWidgets.QLabel(self.groupBox_3)
        self.Discription.setGeometry(QtCore.QRect(10, 40, 271, 21))
        self.Discription.setTextFormat(QtCore.Qt.AutoText)
        self.Discription.setWordWrap(False)
        self.Discription.setObjectName("Discription")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 130, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(320, 180, 111, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(320, 230, 111, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(320, 280, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.stackedWidget_2.addWidget(self.page_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 300, 391, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(75, 25, 241, 241))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/PulseAddones/RobotMovingPanel/images/213422.png"))
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_12.setGeometry(QtCore.QRect(910, 5, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_13.setGeometry(QtCore.QRect(820, 540, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_14.setGeometry(QtCore.QRect(915, 540, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(10, 5, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.textEdit = QtWidgets.QTextEdit(self.page_2)
        self.textEdit.setGeometry(QtCore.QRect(5, 45, 986, 486))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit.setObjectName("textEdit")
        self.stackedWidget.addWidget(self.page_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.tab_3)
        self.stackedWidget_3.setGeometry(QtCore.QRect(0, 0, 1191, 581))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_4.setGeometry(QtCore.QRect(5, 5, 231, 166))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 35, 91, 16))
        self.label_17.setObjectName("label_17")
        self.label_22 = QtWidgets.QLabel(self.page_5)
        self.label_22.setGeometry(QtCore.QRect(10, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_5.setGeometry(QtCore.QRect(245, 5, 931, 166))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_2.setGeometry(QtCore.QRect(65, 60, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 22)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_6 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_6.setGeometry(QtCore.QRect(65, 40, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_6.setFont(font)
        self.progressBar_6.setProperty("value", 22)
        self.progressBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_7.setGeometry(QtCore.QRect(65, 140, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_7.setFont(font)
        self.progressBar_7.setProperty("value", 22)
        self.progressBar_7.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_7.setObjectName("progressBar_7")
        self.progressBar_8 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_8.setGeometry(QtCore.QRect(65, 120, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_8.setFont(font)
        self.progressBar_8.setProperty("value", 22)
        self.progressBar_8.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_8.setObjectName("progressBar_8")
        self.progressBar_9 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_9.setGeometry(QtCore.QRect(65, 100, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_9.setFont(font)
        self.progressBar_9.setProperty("value", 22)
        self.progressBar_9.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_9.setObjectName("progressBar_9")
        self.progressBar_10 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_10.setGeometry(QtCore.QRect(65, 80, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_10.setFont(font)
        self.progressBar_10.setProperty("value", 22)
        self.progressBar_10.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_10.setObjectName("progressBar_10")
        self.progressBar_11 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_11.setGeometry(QtCore.QRect(375, 100, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_11.setFont(font)
        self.progressBar_11.setProperty("value", 22)
        self.progressBar_11.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_11.setObjectName("progressBar_11")
        self.progressBar_12 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_12.setGeometry(QtCore.QRect(375, 80, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_12.setFont(font)
        self.progressBar_12.setProperty("value", 22)
        self.progressBar_12.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_12.setObjectName("progressBar_12")
        self.progressBar_13 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_13.setGeometry(QtCore.QRect(375, 40, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_13.setFont(font)
        self.progressBar_13.setProperty("value", 22)
        self.progressBar_13.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_13.setObjectName("progressBar_13")
        self.progressBar_14 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_14.setGeometry(QtCore.QRect(375, 120, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_14.setFont(font)
        self.progressBar_14.setProperty("value", 22)
        self.progressBar_14.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_14.setObjectName("progressBar_14")
        self.progressBar_15 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_15.setGeometry(QtCore.QRect(375, 140, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_15.setFont(font)
        self.progressBar_15.setProperty("value", 22)
        self.progressBar_15.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_15.setObjectName("progressBar_15")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_3.setGeometry(QtCore.QRect(375, 60, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setProperty("value", 22)
        self.progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_3.setObjectName("progressBar_3")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(40, 40, 16, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(40, 60, 16, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(40, 80, 16, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(40, 100, 16, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(40, 120, 16, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(40, 140, 16, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(315, 40, 16, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(315, 120, 16, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(315, 140, 16, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(315, 80, 16, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(315, 60, 16, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(315, 100, 16, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(625, 40, 16, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(625, 120, 16, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setGeometry(QtCore.QRect(625, 140, 16, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setGeometry(QtCore.QRect(625, 80, 16, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_5)
        self.label_39.setGeometry(QtCore.QRect(625, 60, 16, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_5)
        self.label_40.setGeometry(QtCore.QRect(625, 100, 16, 16))
        self.label_40.setObjectName("label_40")
        self.graphicsView = QtWidgets.QGraphicsView(self.page_5)
        self.graphicsView.setGeometry(QtCore.QRect(5, 210, 1171, 361))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_15.setGeometry(QtCore.QRect(1080, 180, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_5)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 180, 191, 21))
        self.comboBox_2.setMaxVisibleItems(20)
        self.comboBox_2.setMaxCount(10)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_41 = QtWidgets.QLabel(self.page_6)
        self.label_41.setGeometry(QtCore.QRect(10, 5, 86, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.page_6)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 35, 1166, 536))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_16.setGeometry(QtCore.QRect(1095, 5, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.comboBox = QtWidgets.QComboBox(self.page_6)
        self.comboBox.setGeometry(QtCore.QRect(105, 5, 226, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget_3.addWidget(self.page_6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.freezeButton = QtWidgets.QPushButton(Dialog)
        self.freezeButton.setGeometry(QtCore.QRect(820, 615, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.freezeButton.setFont(font)
        self.freezeButton.setObjectName("freezeButton")
        self.relaxButton = QtWidgets.QPushButton(Dialog)
        self.relaxButton.setEnabled(False)
        self.relaxButton.setGeometry(QtCore.QRect(650, 615, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.relaxButton.setFont(font)
        self.relaxButton.setObjectName("relaxButton")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(1030, 615, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalSlider_speed = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_speed.setGeometry(QtCore.QRect(35, 625, 446, 22))
        self.horizontalSlider_speed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_speed.setMinimum(1)
        self.horizontalSlider_speed.setMaximum(100)
        self.horizontalSlider_speed.setSliderPosition(5)
        self.horizontalSlider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_speed.setInvertedAppearance(False)
        self.horizontalSlider_speed.setInvertedControls(False)
        self.horizontalSlider_speed.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_speed.setTickInterval(5)
        self.horizontalSlider_speed.setObjectName("horizontalSlider_speed")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(250, 605, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_42 = QtWidgets.QLabel(Dialog)
        self.label_42.setGeometry(QtCore.QRect(490, 625, 26, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.enableRelaxRadioButton = QtWidgets.QRadioButton(Dialog)
        self.enableRelaxRadioButton.setGeometry(QtCore.QRect(570, 620, 66, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.enableRelaxRadioButton.setFont(font)
        self.enableRelaxRadioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.enableRelaxRadioButton.setObjectName("enableRelaxRadioButton")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget_4.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget_3.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.horizontalSlider_speed.valueChanged['int'].connect(self.label_42.setNum)
        self.freezeButton.clicked.connect(Dialog.freezeRobotHandler)
        self.relaxButton.clicked.connect(Dialog.relaxRobotHandler)
        self.enableRelaxRadioButton.clicked.connect(Dialog.enableRelaxButton)
        self.buttonGroup.buttonClicked['QAbstractButton*'].connect(Dialog.openMoveTabWithSetPointsMode)
        self.addToolButton.clicked.connect(Dialog.addToolHandler)
        self.pushButton_4.clicked.connect(Dialog.setToolName)
        self.tollsComboBox.currentIndexChanged['QString'].connect(Dialog.setToolFromItem)
        self.groupBox_3.clicked.connect(Dialog.setCalibratedTool)
        self.pushButton_3.clicked.connect(Dialog.closeMoveTab)
        self.pushButton_2.clicked.connect(Dialog.setCalibratedPoint)
        self.pushButton.clicked.connect(Dialog.goHome)
        self.treeWidget.itemClicked['QTreeWidgetItem*','int'].connect(Dialog.showProgramEditor)
        self.pushButton_12.clicked.connect(Dialog.showFileDialog)
        self.pushButton_14.clicked.connect(Dialog.runCode)
        self.pushButton_13.clicked.connect(Dialog.saveProgramHandler)
        self.removeToolButton.clicked.connect(Dialog.delToolHandler)
        self.setTool_Button.clicked.connect(Dialog.setToolHandler)
        self.resetToll_Button.clicked.connect(Dialog.resetTool)
        self.setPoints_Button.clicked.connect(Dialog.openToolSetPoints)
        self.SetToolPointsButton.clicked.connect(Dialog.setCalibratedTool)
        self.pushButton_16.clicked.connect(Dialog.closeGraphWindow)
        self.radioButton_Jogging.clicked.connect(self.radioButton_Step.lower)
        self.pushButton_15.clicked.connect(Dialog.openFullScreen)
        self.radioButton_Step.clicked.connect(self.radioButton_Jogging.lower)
        self.radioButton_Step.clicked.connect(Dialog.enableStepEnter)
        self.radioButton_Jogging.clicked.connect(Dialog.enableStepEnter)
        self.cancelSetToolPointsButton.clicked.connect(Dialog.closeTeachTCPWindow)
        self.buttonGroup.buttonClicked['int'].connect(Dialog.teachToolPointsChecker)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Move Tool"))
        self.label_move_step.setText(_translate("Dialog", "Linear Step"))
        self.label_move_step_2.setText(_translate("Dialog", "Rotation Step"))
        self.label_43.setText(_translate("Dialog", "mm"))
        self.label_44.setText(_translate("Dialog", "deg"))
        self.groupBox_8.setTitle(_translate("Dialog", "Move Type"))
        self.radioButton_Step.setText(_translate("Dialog", "Steps"))
        self.radioButton_Jogging.setText(_translate("Dialog", "Jogging"))
        self.pushButton.setText(_translate("Dialog", "Go Home"))
        self.pushButton_2.setText(_translate("Dialog", "OK"))
        self.pushButton_3.setText(_translate("Dialog", "Cancel"))
        self.button_xUp.setText(_translate("Dialog", "X+"))
        self.button_yUp.setText(_translate("Dialog", "Y+"))
        self.button_zUp.setText(_translate("Dialog", "Z+"))
        self.button_rollUp.setText(_translate("Dialog", "RX+"))
        self.button_pitchUp.setText(_translate("Dialog", "RY+"))
        self.button_yawUp.setText(_translate("Dialog", "RZ+"))
        self.button_xDown.setText(_translate("Dialog", "X-"))
        self.button_yDown.setText(_translate("Dialog", "Y-"))
        self.button_zDown.setText(_translate("Dialog", "Z-"))
        self.button_rollDown.setText(_translate("Dialog", "RX-"))
        self.button_pitchDown.setText(_translate("Dialog", "RY-"))
        self.button_yawDown.setText(_translate("Dialog", "RZ-"))
        self.button_JUp_1.setText(_translate("Dialog", "J1+"))
        self.button_JUp_2.setText(_translate("Dialog", "J2+"))
        self.button_JUp_3.setText(_translate("Dialog", "J3+"))
        self.button_JUp_4.setText(_translate("Dialog", "J4+"))
        self.button_JUp_5.setText(_translate("Dialog", "J5+"))
        self.button_JUp_6.setText(_translate("Dialog", "J6+"))
        self.button_JDown_1.setText(_translate("Dialog", "J1-"))
        self.button_JDown_2.setText(_translate("Dialog", "J2-"))
        self.button_JDown_3.setText(_translate("Dialog", "J3-"))
        self.button_JDown_4.setText(_translate("Dialog", "J4-"))
        self.button_JDown_5.setText(_translate("Dialog", "J5-"))
        self.button_JDown_6.setText(_translate("Dialog", "J6-"))
        self.label_rotation_step.setText(_translate("Dialog", "Rotation Step, deg"))
        self.groupBox_9.setTitle(_translate("Dialog", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Dialog", "Move"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Dialog", "General"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Dialog", "TCP"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Dialog", "Program"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Dialog", "Features"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Dialog", "Point"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Dialog", "Line"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Dialog", "Plane"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("Dialog", "Tool Center Point"))
        self.lineEdit_tollX.setText(_translate("Dialog", "0.0"))
        self.lineEdit_tool_Y.setText(_translate("Dialog", "0.0"))
        self.lineEdit_tool_Z.setText(_translate("Dialog", "0.0"))
        self.lineEdit_tool_RX.setText(_translate("Dialog", "0.0"))
        self.lineEdit_tool_RY.setText(_translate("Dialog", "0.0"))
        self.lineEdit_tool_RZ.setText(_translate("Dialog", "0.0"))
        self.label.setText(_translate("Dialog", "X:"))
        self.label_2.setText(_translate("Dialog", "Y:"))
        self.label_3.setText(_translate("Dialog", "Z:"))
        self.label_4.setText(_translate("Dialog", "mm"))
        self.label_5.setText(_translate("Dialog", "mm"))
        self.label_6.setText(_translate("Dialog", "mm"))
        self.label_7.setText(_translate("Dialog", "RX:"))
        self.label_8.setText(_translate("Dialog", "RY:"))
        self.label_9.setText(_translate("Dialog", "RZ:"))
        self.label_10.setText(_translate("Dialog", "rad"))
        self.label_11.setText(_translate("Dialog", "rad"))
        self.label_12.setText(_translate("Dialog", "rad"))
        self.label_13.setText(_translate("Dialog", "Position"))
        self.label_14.setText(_translate("Dialog", "Orientation"))
        self.resetToll_Button.setText(_translate("Dialog", "Reset"))
        self.setPoints_Button.setText(_translate("Dialog", "Teach"))
        self.setTool_Button.setText(_translate("Dialog", "Set Tool"))
        self.tollsComboBox.setItemText(0, _translate("Dialog", "default"))
        self.addToolButton.setText(_translate("Dialog", "+"))
        self.removeToolButton.setText(_translate("Dialog", "-"))
        self.pushButton_4.setText(_translate("Dialog", "Change Name"))
        self.groupBox_7.setTitle(_translate("Dialog", "Robot Frames"))
        self.groupBox_3.setTitle(_translate("Dialog", "Teach TCP Position"))
        self.setToolPoint_1_Button.setText(_translate("Dialog", "Set Point 1"))
        self.setToolPoint_2_Button.setText(_translate("Dialog", "Set Point 2"))
        self.setToolPoint_3_Button.setText(_translate("Dialog", "Set Point 3"))
        self.setToolPoint_4_Button.setText(_translate("Dialog", "Set Point 4"))
        self.SetToolPointsButton.setText(_translate("Dialog", "Set"))
        self.cancelSetToolPointsButton.setText(_translate("Dialog", "Cancel"))
        self.Discription.setText(_translate("Dialog", "Move the TCP to the same position from different angles."))
        self.pushButton_5.setText(_translate("Dialog", "Move to point"))
        self.pushButton_6.setText(_translate("Dialog", "Move to point"))
        self.pushButton_7.setText(_translate("Dialog", "Move to point"))
        self.pushButton_8.setText(_translate("Dialog", "Move to point"))
        self.groupBox_6.setTitle(_translate("Dialog", "Flange"))
        self.pushButton_12.setText(_translate("Dialog", "Open"))
        self.pushButton_13.setText(_translate("Dialog", "Save"))
        self.pushButton_14.setText(_translate("Dialog", "Run"))
        self.label_21.setText(_translate("Dialog", "Programm editor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Instalation"))
        self.groupBox_4.setTitle(_translate("Dialog", "Readings"))
        self.label_17.setText(_translate("Dialog", "Main Voltage"))
        self.label_22.setText(_translate("Dialog", "Graphics"))
        self.groupBox_5.setTitle(_translate("Dialog", "Joints Load"))
        self.progressBar_2.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_6.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_7.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_8.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_9.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_10.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_11.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_12.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_13.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_14.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_15.setFormat(_translate("Dialog", "%p%"))
        self.progressBar_3.setFormat(_translate("Dialog", "%p%"))
        self.label_23.setText(_translate("Dialog", "1"))
        self.label_24.setText(_translate("Dialog", "2"))
        self.label_25.setText(_translate("Dialog", "3"))
        self.label_26.setText(_translate("Dialog", "4"))
        self.label_27.setText(_translate("Dialog", "5"))
        self.label_28.setText(_translate("Dialog", "6"))
        self.label_29.setText(_translate("Dialog", "A"))
        self.label_30.setText(_translate("Dialog", "A"))
        self.label_31.setText(_translate("Dialog", "A"))
        self.label_32.setText(_translate("Dialog", "A"))
        self.label_33.setText(_translate("Dialog", "A"))
        self.label_34.setText(_translate("Dialog", "A"))
        self.label_35.setText(_translate("Dialog", "V"))
        self.label_36.setText(_translate("Dialog", "V"))
        self.label_37.setText(_translate("Dialog", "V"))
        self.label_38.setText(_translate("Dialog", "V"))
        self.label_39.setText(_translate("Dialog", "V"))
        self.label_40.setText(_translate("Dialog", "V"))
        self.pushButton_15.setText(_translate("Dialog", "Full Screen"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "New Item"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "New Item"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "New Item"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "New Item"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "New Item"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "New Item"))
        self.label_41.setText(_translate("Dialog", "Graphics"))
        self.pushButton_16.setText(_translate("Dialog", "Close"))
        self.comboBox.setItemText(0, _translate("Dialog", "New Item"))
        self.comboBox.setItemText(1, _translate("Dialog", "New Item"))
        self.comboBox.setItemText(2, _translate("Dialog", "New Item"))
        self.comboBox.setItemText(3, _translate("Dialog", "New Item"))
        self.comboBox.setItemText(4, _translate("Dialog", "New Item"))
        self.comboBox.setItemText(5, _translate("Dialog", "New Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Page"))
        self.freezeButton.setText(_translate("Dialog", "Freeze"))
        self.relaxButton.setText(_translate("Dialog", "Relax"))
        self.label_15.setText(_translate("Dialog", "Rozum Robotics"))
        self.label_18.setText(_translate("Dialog", "Speed"))
        self.label_42.setText(_translate("Dialog", "5"))
        self.enableRelaxRadioButton.setText(_translate("Dialog", "Enable"))
